[package]
name = "copyright-check"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0 OR GPL-3.0-or-later"

[dependencies]
anyhow = "1.0.86"
clap = {version = "=4.5.6", features = ["derive", "wrap_help"]}
liso = "1.2.1"
regex = "1.10.5"
